app.sylius_payment:
  class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
  arguments: [ MaadamSolutions\SyliusZettlePlugin\Payum\SyliusPaymentGatewayFactory ]
  tags:
    - { name: payum.gateway_factory_builder, factory: sylius_zettle }

MaadamSolutions\SyliusZettlePlugin\Form\Type\SyliusGatewayConfigurationType:
  tags:
    - { name: sylius.gateway_configuration_type, type: sylius_payment, label: 'Sylius Payment' }
    - { name: form.type }

MaadamSolutions\SyliusZettlePlugin\Payum\Action\CaptureAction:
  arguments:
    - '@sylius.http_client'
  tags:
    - { name: payum.action, factory: sylius_zettle, alias: payum.action.capture }